### PR TITLE
Add MenuItem::Check

### PR DESCRIPTION
**Pull request by ab5tract**
This deviates a bit from our standard approach of adding a new widget as a `GTK::Simple` class. I'm open to debate the merits of this approach / whether it needs to be normalized against the existing `GTK::Simple` approach or whether we should/could instead push `GTK::Simple` more towards an inheritance based hierarchy.

### CODE REVIEW

**Comment by finanalyst** [comment]
Just looking at the diff, I'm not sure of the extent to which your changes deviate from the GTK::Simple standard approach. If you could provide some commentary that would be useful.

I would prefer to have a single canonical approach, whatever that is, than to have different approaches.
But that is not to say that the approach so far is optimal, or that there are not better ways of inheriting functionality. 

My overall view is that GTK::Simple (while we develop it using GTK3) should be modified to the **minimum useful** extent. I tend to add widgets to GTK::Simple to meet my own needs. 

My thought here is that effort to clean up `GTK::Simple:ver(3)` may be better spent on getting `:api(4)` working. But I am willing to accept that `:ver(3)` is going to be around for a long time yet,
so making it more useful (adding widgets) is a good thing.

I think our focus should be on a `GTK::Simple:api(4)` module, and that we develop a way to include widgets automagically from the GTK4 descriptions.

**Comment by ab5tract** [comment]
I think there are two different approaches in the `GTK::Simple` codebase already. One is to always have a single class that maps directly to the underling GTK class: in this PR, this would mean that `MenuItem::Check` should instead be `CheckMenuItem`. This would match how we have both `Button` and `CheckButton`.

Another approach, already present in `GTK::Simple` via `ListBox::Row` as opposed to `ListBoxRow` (and I thought some other places, but I couldn't find another example). `ListBox::Row` is unlikely to be used directly, so it is maybe a special case.

I think maybe it would be better for me to align this PR to the more general standard, making this a `CheckMenuItem`.

I'm a bit confused about your usage of `:ver(3)` and `:api(4)` -- shouldn't that be `:api(3)` vs `:api(4)`? Also, it may be interesting to note that `:api` can hold strings, meaning we could use `:api('gtk4')` if that was decided to be clearer.

**Comment by finanalyst** [comment]
> I'm a bit confused about your usage of :ver(3) and :api(4) -- shouldn't that be :api(3) vs :api(4)? 

My bad. I was using them interchangably. It seems to me that GTK4 is a bit more than a version change, so maybe `api` would be better. I also agree that `api<gkt4>` may be more informative.

**Comment by finanalyst** [comment]
Seems good. Merging

**Comment by ab5tract** [comment]
Hey @finanalyst , it looks like this didn't actually get merged?

**Comment by finanalyst** [comment]
My bad, I closed the PR without merging. Merged now

**Pull request merged**
