### PR TITLE
Add attach method to GTK::Simple::Grid

### PR DESCRIPTION
**Pull request by finanalyst**
After a Grid has been created, new Widgets can be attached in the same way as for the new method

### CODE REVIEW

**Comment by lizmat** [comment]
Thanks for this PR!   Could I interest you in taking over maintenance of this module completely?  As at least I do not have the means to actually check the validity or appropriateness of your PR.  Which you clearly have some of?  :-)

**Comment by lizmat** [comment]
Ah, I see you've changed the auth, so I'd say that's a yes to my question?

**Comment by finanalyst** [comment]
@lizmat Actually, I was trying to ad the auth only to my fork.

**Comment by finanalyst** [comment]
I'm not sure I can completely maintain as this module has major issues with MS Windows, and I don't know how to handle them. The issue is that for Windows, there need to be dll. I don't know how to generate them.

**Comment by lizmat** [comment]
@finanalyst hopefully someone with Windows chops will come along later  :-)

**Comment by lizmat** [comment]
@finanalyst I suggest we close this PR, change the reference in the ecosystem to your repo, and archive this module in raku-community-modules.  That will give you complete control and this module will have a new active maintainer!  Please don't let the impostor syndrome get the better of you!

**Comment by finanalyst** [comment]
@lizmat OK. I reverted the commit with the version number and auth.
So what should I do?
a) bump the version again
b) Add myself to authors
Anything else?

**Comment by lizmat** [comment]
Make sure that your repo is up to date with the new version.  I will then change the ecosystem reference to point to your repo.  And that should be it, afaik.

**Comment by finanalyst** [comment]
@lizmat I just updated my repo to the new version, so the only difference is the commits I made

**Comment by lizmat** [comment]
https://github.com/Raku/ecosystem/commit/1427c46ca0  Closing this PR now.

I tried to transfer this repo, with its issues and PR's to you, but Github wouldn't let me.  Please let me know if you'd like to pursue this.

**Comment by finanalyst** [comment]
@lizmat  I tried sending you an email. I'm happy to continue with a transfer. Please let me know what to do.
Part of the problem, I think, is the Travis CI configuration.

**Comment by lizmat** [comment]
@finanalyst could you delete your GTK-Simple fork from Github (but keep your local copy).  It looks like the fork is now inhibiting a transfer to you.

**Comment by JJ** [comment]
> [Raku/ecosystem@1427c46](https://github.com/Raku/ecosystem/commit/1427c46ca0) Closing this PR now.
> 
> I tried to transfer this repo, with its issues and PR's to you, but Github wouldn't let me. Please let me know if you'd like to pursue this.

The way to go is to make the transferee owner of this repo too. I can do that if you want.

**Comment by Xliff** [comment]
@finalyst, if you would like a co-conspirator in maintenance work, I'd like to help Especially considering my work in [what could only be considered as GTK::Complex](https://github.com/Xliff/p6-GtkPlus).

**Pull request closed without merging**
