### PR TITLE
Refactor all inner classes and roles into their own files under GTK::Simple namespace

### PR DESCRIPTION
**Pull request by azawawi**
This also moves nativecall stuff into `GTK::Simple::Raw`

### CODE REVIEW

**Comment by MadcapJake** [comment]
Does this work? I didn't think you could just `use` sub-modules into a main module file like that.

**Comment by jonathanstowe** [comment]
It works, though the first time it doesn't which is probably some artefact of the precompiled stuff not being cleaned up properly.

Anyhow, the tests pass and all the example work so in principle I'm good with it, would still like to get other opinion before merging though.  If no-one says "OHMIGOD YOU CAN'T DO THAT, THINK OF THE KITTENS" before this evening I'll merge.

**Comment by finanalyst** [comment]
Looked at changes. Very sensible. Adding a new widget is now just adding another file rather than messing with the main module.

I'll work on getting a better intro text

**Comment by jonathanstowe** [comment]
Right going to do this now :)

**Comment by azawawi** [comment]
Thanks :+1:

**Comment by slobo** [comment]
(OT) Re: precompiled assets - first time I tired to re-run after syncing it took good 2-3 minutes of 100% CPU. And then it would either crash or say that it can't find GTK::Simple::Window for any of the examples. Had to remove all .precomp I could find to get it to wise-up.

**Comment by finanalyst** [comment]
Same problem for me.
I used
panda --force install GTK::Simple

Whenever I had worked on gtk-simple in my repo or when re-installing 
from the internet, panda handled everything quite well.

This indicates there is a problem with panda when a module has been 
radically refactored.

**Comment by finanalyst** [comment]
In trying to sort this out, I screwed up the whole perl6 ecosytem and 
had to reinstall from scratch. Not good.

**Comment by azawawi** [comment]
I am working on it. Please see https://github.com/perl6/gtk-simple/issues/34. Sorry for any inconvenience.

**Comment by jonathanstowe** [comment]
Strange, it worked fine when I tested it first. However, installed it may not work because it is missing the split out modules in the "provides" of the META6.json

**Pull request merged**
